(() => {
  const token = () => localStorage.getItem('rota_token') || '';
  const css = `#rotaCommissionFab{position:fixed;right:16px;bottom:88px;z-index:9000;padding:12px 15px;border-radius:14px;background:linear-gradient(135deg,#ffb300,#ffe16a);color:#111;font-weight:950;box-shadow:0 12px 32px #0008;border:1px solid #fff3}#rotaCommissionModal{position:fixed;inset:0;z-index:10000;display:none;place-items:center;padding:16px;background:rgba(1,7,18,.94)}#rotaCommissionModal.open{display:grid}.rc-card{width:min(480px,100%);max-height:90vh;overflow:auto;padding:22px;border-radius:24px;background:linear-gradient(145deg,#082448,#041427);border:1px solid #25c8ff88;box-shadow:0 24px 80px #000b}.rc-card h2{margin:0 0 6px}.rc-sub{color:#9fb8d3;font-size:13px;margin-bottom:16px}.rc-card input{width:100%;padding:13px;margin:6px 0 12px;background:#06162d;border:1px solid #214d7c;border-radius:12px;color:#fff}.rc-actions{display:flex;gap:8px;flex-wrap:wrap}.rc-btn{padding:12px 15px;border-radius:12px;border:1px solid #28577e;background:#09264b;color:#fff;font-weight:900}.rc-btn.primary{background:linear-gradient(135deg,#00b96b,#22e89b);color:#062016}.rc-btn.close{background:#071a35}.rc-result{margin-top:16px;display:grid;gap:9px}.rc-row{display:flex;justify-content:space-between;gap:10px;padding:12px;border-radius:13px;background:#071a35;border:1px solid #173f69}.rc-row strong.green{color:#20e890}.rc-row strong.gold{color:#ffd35b}.rc-note{margin-top:12px;color:#87a6c8;font-size:11px;line-height:1.4}`;
  const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
  const fab=document.createElement('button');fab.id='rotaCommissionFab';fab.textContent='💰 Testar 5%';document.body.appendChild(fab);
  const modal=document.createElement('div');modal.id='rotaCommissionModal';modal.innerHTML=`<div class="rc-card"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><h2>💰 Teste de Comissão ROTA</h2><button class="rc-btn close" id="rcClose">×</button></div><div class="rc-sub">Simulação interna: nenhuma transferência de dinheiro real acontece.</div><label>Valor bruto da entrega</label><input id="rcAmount" inputmode="decimal" value="100,00" placeholder="100,00"><label>Referência da entrega</label><input id="rcRef" value="TESTE-${Date.now()}" placeholder="Ex.: TESTE-001"><div class="rc-actions"><button class="rc-btn primary" id="rcSettle">Calcular e registrar teste</button><button class="rc-btn" id="rcWallet">Atualizar carteira</button></div><div id="rcResult" class="rc-result"></div><div class="rc-note">Regra atual do teste: 5% para a carteira da plataforma ROTA e 95% para a carteira do entregador. O saldo é apenas contábil de teste.</div></div>`;document.body.appendChild(modal);
  const result=modal.querySelector('#rcResult');const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(v)||0)/100);const cents=s=>{const x=String(s||'').replace(/\s/g,'').replace(/\./g,'').replace(',','.');const n=Number(x);return Number.isFinite(n)?Math.round(n*100):0};const showError=e=>{result.innerHTML=`<div class="rc-row"><span>⚠️</span><strong>${String(e.message||e)}</strong></div>`};
  async function api(path,options={}){const t=token();if(!t)throw Error('Faça login no ROTA antes de usar o teste.');const r=await fetch(path,{...options,headers:{'Content-Type':'application/json','Authorization':'Bearer '+t,...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Falha ao consultar o backend.');return d}
  async function wallet(){try{const d=await api('/api/test/wallet');result.innerHTML=`<div class="rc-row"><span>🏦 Carteira ROTA</span><strong class="gold">${money(d.platform_cents)}</strong></div><div class="rc-row"><span>🛵 Carteira entregador</span><strong class="green">${money(d.driver_cents)}</strong></div><div class="rc-row"><span>📊 Total contábil teste</span><strong>${money(d.total_cents)}</strong></div>`}catch(e){showError(e)}}
  async function settle(){try{result.innerHTML='<div class="rc-row"><span>⏳</span><span>Registrando simulação…</span></div>';const gross=cents(document.getElementById('rcAmount').value);if(gross<=0)throw Error('Informe um valor maior que zero.');const ref=document.getElementById('rcRef').value.trim()||('TESTE-'+Date.now());const d=await api('/api/test/delivery-settle',{method:'POST',body:JSON.stringify({delivery_ref:ref,gross_amount_cents:gross})});const s=d.settlement;result.innerHTML=`<div class="rc-row"><span>💰 Total bruto</span><strong>${money(s.gross_amount_cents)}</strong></div><div class="rc-row"><span>🏦 Comissão ROTA (5%)</span><strong class="gold">${money(s.commission_cents)}</strong></div><div class="rc-row"><span>🛵 Entregador (95%)</span><strong class="green">${money(s.driver_net_cents)}</strong></div><div class="rc-row"><span>📌 Referência</span><strong>${s.delivery_ref}</strong></div>`}catch(e){showError(e)}}
  fab.onclick=()=>{modal.classList.add('open');result.innerHTML='';document.getElementById('rcAmount').focus()};modal.querySelector('#rcClose').onclick=()=>modal.classList.remove('open');modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});modal.querySelector('#rcSettle').onclick=settle;modal.querySelector('#rcWallet').onclick=wallet;
})();
