(() => {
  const getToken=()=>localStorage.getItem('rota_token')||'';
  const api=async(path,options={})=>{const t=getToken();if(!t)throw Error('Faça login para continuar.');const r=await fetch(path,{...options,headers:{'Content-Type':'application/json','Authorization':'Bearer '+t,...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Não foi possível concluir a ação.');return d};
  const css=`#rotaCoreFab{position:fixed;right:16px;bottom:145px;z-index:8999;padding:11px 14px;border-radius:14px;background:#071a35;border:1px solid #26cfff;color:#fff;font-weight:900;box-shadow:0 12px 30px #0008}#rotaCorePanel{position:fixed;inset:0;z-index:10001;display:none;place-items:center;padding:16px;background:#010713ee}#rotaCorePanel.open{display:grid}.rco{width:min(520px,100%);max-height:90vh;overflow:auto;padding:20px;border-radius:24px;background:linear-gradient(145deg,#082448,#041427);border:1px solid #26cfff77}.rco h2{margin:0 0 5px}.rco small{color:#91afd0}.rco .rrow{display:flex;justify-content:space-between;gap:10px;padding:12px;margin:7px 0;border-radius:13px;background:#071a35;border:1px solid #173f69}.rco button{padding:11px 13px;border-radius:12px;background:#09264b;border:1px solid #28577e;color:#fff;font-weight:850;margin:4px 3px 4px 0}.rco .ok{background:linear-gradient(135deg,#00b96b,#22e89b);color:#062016}.rco .danger{background:#481b27;border-color:#9b3a51}.rco .muted{color:#9fb8d3;font-size:12px}`;
  const s=document.createElement('style');s.textContent=css;document.head.appendChild(s);
  const fab=document.createElement('button');fab.id='rotaCoreFab';fab.textContent='🧭 Ações rápidas';document.body.appendChild(fab);
  const panel=document.createElement('div');panel.id='rotaCorePanel';panel.innerHTML=`<div class="rco"><div style="display:flex;justify-content:space-between;align-items:center"><div><h2>🧭 ROTA — Ações rápidas</h2><small>Menos telas, mais ações que funcionam.</small></div><button id="rcoClose">×</button></div><div id="rcoBody" style="margin-top:14px"><div class="rrow"><span>🔐 Sessão</span><strong id="rcoRole">Verificando…</strong></div><button class="ok" id="rcoNew">📦 Nova entrega</button><button id="rcoMine">📍 Minhas entregas</button><button id="rcoNotify">🔔 Notificações</button><button id="rcoLogout" class="danger">Sair</button><div class="muted">Ações financeiras reais continuam protegidas pelo backend e não aparecem aqui como se fossem transferência.</div></div></div>`;document.body.appendChild(panel);
  const body=panel.querySelector('#rcoBody');
  async function session(){try{const d=await api('/api/auth/me');panel.querySelector('#rcoRole').textContent=d.user.role;return d.user}catch(e){panel.querySelector('#rcoRole').textContent='Não autenticado';return null}}
  async function mine(){try{const d=await api('/api/deliveries');const rows=d.deliveries||[];body.innerHTML='<h3>📍 Minhas entregas</h3>'+ (rows.length?rows.slice(0,12).map(x=>`<div class="rrow"><span>📦 ${x.origin}<br>→ ${x.destination}</span><strong>${x.status}</strong></div>`).join(''):'<div class="rrow"><span>Nenhuma entrega ainda.</span></div>')+'<button id="rcoBack">Voltar</button>';panel.querySelector('#rcoBack').onclick=home}catch(e){body.innerHTML=`<div class="rrow"><strong>${e.message}</strong></div><button id="rcoBack">Voltar</button>`;panel.querySelector('#rcoBack').onclick=home}}
  async function notify(){try{const d=await api('/api/notifications');const rows=d.notifications||[];body.innerHTML='<h3>🔔 Notificações</h3>'+ (rows.length?rows.slice(0,12).map(x=>`<div class="rrow"><span><strong>${x.title}</strong><br><small>${x.message}</small></span><strong>${x.read_at?'':'•'}</strong></div>`).join(''):'<div class="rrow"><span>Você está em dia.</span></div>')+'<button id="rcoBack">Voltar</button>';panel.querySelector('#rcoBack').onclick=home}catch(e){body.innerHTML=`<div class="rrow"><strong>${e.message}</strong></div><button id="rcoBack">Voltar</button>`;panel.querySelector('#rcoBack').onclick=home}}
  function home(){body.innerHTML=`<div class="rrow"><span>🔐 Sessão</span><strong id="rcoRole">Verificando…</strong></div><button class="ok" id="rcoNew">📦 Nova entrega</button><button id="rcoMine">📍 Minhas entregas</button><button id="rcoNotify">🔔 Notificações</button><button id="rcoLogout" class="danger">Sair</button><div class="muted">Ações financeiras reais continuam protegidas pelo backend.</div>`;bind();session()}
  function bind(){panel.querySelector('#rcoMine').onclick=mine;panel.querySelector('#rcoNotify').onclick=notify;panel.querySelector('#rcoNew').onclick=()=>{body.innerHTML='<h3>📦 Nova entrega</h3><input id="rcoO" placeholder="Origem" style="width:100%;padding:12px;margin:6px 0;background:#06162d;color:#fff;border:1px solid #214d7c;border-radius:10px"><input id="rcoD" placeholder="Destino" style="width:100%;padding:12px;margin:6px 0;background:#06162d;color:#fff;border:1px solid #214d7c;border-radius:10px"><button class="ok" id="rcoCreate">Criar pedido</button><button id="rcoBack">Voltar</button>';panel.querySelector('#rcoCreate').onclick=async()=>{try{const origin=panel.querySelector('#rcoO').value.trim(),destination=panel.querySelector('#rcoD').value.trim();if(!origin||!destination)throw Error('Informe origem e destino.');const d=await api('/api/deliveries',{method:'POST',body:JSON.stringify({origin,destination,amount_cents:0})});body.innerHTML=`<div class="rrow"><span>✅ Pedido criado</span><strong>${d.delivery.status}</strong></div><div class="rrow"><span>${d.delivery.origin}</span><strong>→</strong></div><div class="rrow"><span>${d.delivery.destination}</span><strong>ROTA</strong></div><button id="rcoBack">Voltar</button>`;panel.querySelector('#rcoBack').onclick=home}catch(e){alert(e.message)}};panel.querySelector('#rcoBack').onclick=home};panel.querySelector('#rcoLogout').onclick=()=>{localStorage.removeItem('rota_token');localStorage.removeItem('rota_user');location.reload()}}
  fab.onclick=async()=>{panel.classList.add('open');home()};panel.querySelector('#rcoClose').onclick=()=>panel.classList.remove('open');panel.addEventListener('click',e=>{if(e.target===panel)panel.classList.remove('open')});bind();
})();