(() => {
  const token=()=>localStorage.getItem('rota_token')||'';
  const api=async(path,options={})=>{const t=token();if(!t)throw Error('Faça login no ROTA para acompanhar suas entregas.');const r=await fetch(path,{...options,headers:{'Content-Type':'application/json','Authorization':'Bearer '+t,...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Não foi possível consultar o ROTA.');return d};
  const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(v)||0)/100);
  const labels={CREATED:'Pedido criado',SEARCHING_DRIVER:'Procurando entregador',ACCEPTED:'Entregador aceitou',PICKED_UP:'Pedido coletado',IN_TRANSIT:'Em rota',DELIVERED:'Entregue',CANCELLED:'Cancelado'};
  const css=`#rotaTrackFab{position:fixed;right:16px;bottom:142px;z-index:8999;padding:11px 14px;border-radius:14px;background:#082b55;border:1px solid #27cfff;color:#fff;font-weight:900;box-shadow:0 10px 28px #0008}#rotaTrackModal{position:fixed;inset:0;z-index:10001;display:none;place-items:center;padding:16px;background:rgba(1,7,18,.94)}#rotaTrackModal.open{display:grid}.rt-card{width:min(520px,100%);max-height:90vh;overflow:auto;padding:22px;border-radius:24px;background:linear-gradient(145deg,#082448,#041427);border:1px solid #25c8ff88;box-shadow:0 24px 80px #000b}.rt-card h2{margin:0 0 5px}.rt-sub{color:#9fb8d3;font-size:13px;margin-bottom:15px}.rt-row{padding:13px;border-radius:14px;background:#071a35;border:1px solid #173f69;margin:8px 0}.rt-btn{padding:11px 14px;border-radius:12px;background:#09264b;border:1px solid #28577e;color:#fff;font-weight:900;margin:4px}.rt-btn.primary{background:linear-gradient(135deg,#087cff,#00d9ff)}.rt-btn.green{background:linear-gradient(135deg,#00b96b,#22e89b);color:#062016}.rt-muted{color:#87a6c8;font-size:12px}.rt-track{display:grid;grid-template-columns:repeat(7,1fr);gap:4px;margin:15px 0}.rt-dot{height:9px;border-radius:9px;background:#173654}.rt-dot.on{background:#20e890;box-shadow:0 0 12px #20e890}.rt-actions{display:flex;flex-wrap:wrap;gap:5px}`;
  const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
  const fab=document.createElement('button');fab.id='rotaTrackFab';fab.textContent='📍 Acompanhar';document.body.appendChild(fab);
  const modal=document.createElement('div');modal.id='rotaTrackModal';modal.innerHTML='<div class="rt-card"><div style="display:flex;justify-content:space-between;align-items:center;gap:10px"><div><h2>📍 Acompanhar no ROTA</h2><div class="rt-sub">Veja o andamento das suas entregas e suas notificações.</div></div><button class="rt-btn" id="rtClose">×</button></div><div id="rtBody"></div></div>';document.body.appendChild(modal);const body=modal.querySelector('#rtBody');
  const order=['CREATED','SEARCHING_DRIVER','ACCEPTED','PICKED_UP','IN_TRANSIT','DELIVERED'];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function render(){try{const [dd,nn]=await Promise.all([api('/api/deliveries'),api('/api/notifications')]);const ds=dd.deliveries||[],ns=nn.notifications||[];body.innerHTML=`<div class="rt-row"><strong>📦 ${ds.length}</strong> entrega(s) no seu histórico <span class="rt-muted"> · ${ns.filter(n=>!n.read_at).length} aviso(s) não lido(s)</span></div>`+(ds.length?ds.slice(0,12).map(d=>{const idx=Math.max(0,order.indexOf(d.status));const pct=d.status==='CANCELLED'?0:Math.round((idx/(order.length-1))*100);return `<div class="rt-row"><strong>${esc(d.origin)} → ${esc(d.destination)}</strong><div class="rt-muted">${esc(labels[d.status]||d.status)}${d.amount_cents!=null?' · '+money(d.amount_cents):''}</div><div class="rt-track">${order.map((_,i)=>`<i class="rt-dot ${i<=idx&&d.status!=='CANCELLED'?'on':''}"></i>`).join('')}</div><div class="rt-muted">Progresso: ${pct}%</div></div>`}).join(''):'<div class="rt-row">Você ainda não possui entregas.</div>')+`<div class="rt-row"><strong>🔔 Notificações</strong>${ns.length?ns.slice(0,8).map(n=>`<div style="margin-top:9px"><b>${esc(n.title)}</b><div class="rt-muted">${esc(n.message)}</div>${!n.read_at?`<button class="rt-btn" data-read="${n.id}">Marcar como lida</button>`:''}</div>`).join(''):'<div class="rt-muted" style="margin-top:8px">Nenhuma notificação.</div>'}</div><div class="rt-actions"><button class="rt-btn primary" id="rtRefresh">Atualizar</button></div>`;body.querySelector('#rtRefresh').onclick=render;body.querySelectorAll('[data-read]').forEach(b=>b.onclick=async()=>{await api('/api/notifications/'+b.dataset.read+'/read',{method:'POST'});render()})}catch(e){body.innerHTML=`<div class="rt-row"><strong>⚠️ ${esc(e.message)}</strong></div>`}}
  fab.onclick=()=>{modal.classList.add('open');render()};modal.querySelector('#rtClose').onclick=()=>modal.classList.remove('open');modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});
})();